### ISSUE TITLE
Теперь без негатива😳

### ISSUE THREAD

**Issue by netstrex** [xartd0/RESH-ANSWERS#1]
Рад, что ты послушал, то что я пытался донести в предыдущем issue, и код рили стал лучше. Но потом, когда проект действительно вырастет, или над ним начнет работать больше одного человека, советую тебе сделать: отдельные классы для авторизации, и отдельрые классы для получения ответов. Для каждоготипа заданий, в классе будет отдельный метод. Это во много раз улучшит читаемость кода + ты можешь создать абстрактный класс с общими методами для авторизации/получения ответов во всех сервисах, и наследовать все от него. 
Так ты можешь сократить количество повторяющегося кода + изменять какие-то общие вещи сразу для всех классов, не трогая каждый из них отдельно :)

**Comment by xartd0** [comment]
:)

**Comment by xartd0** [comment]
Спасибо за критику,но думаю,что больше не буду заниматься этим проектом. Но применю твои советы в других)
