### ISSUE TITLE
На многие вопросы нет ответов

### ISSUE THREAD

**Issue by prtolem** [xartd0/RESH-ANSWERS#2]
задание:
![image](https://user-images.githubusercontent.com/66413287/155682728-9dc729d2-efd5-461e-ab6c-315c28347a0c.png)

Ответ: 
`№3📝Вопрос: Ответьте на вопросы, чтобы увидеть рисунок. Для каждого верного утверждения поставьте «1», для каждого неверного утверждения – «0». 
`
а ответа нет

**Comment by xartd0** [comment]
Я же написал в репозитории,что скрипт поддерживает мало типов заданий
